### ISSUE TITLE
I trying to build n qmake  n make but its didn't work

### ISSUE THREAD

**Issue by samdhadve** [vranki/kittinger#2]
When I try to run this command in raspberry pi 4
To build:

sudo apt-get install libgps-dev libgnokii-dev libqt4-dev
qmake
make
 In step qmake  get error  cannot generate makfile for this 
What should i do

**Comment by vranki** [comment]
Try now - the project is quite outdated and assumed Qt 4. I upgraded it to build on Qt5.
